site_name: Carolina Projects
site_url: https://mydomain.org/mysite
theme:
  name: material
  palette:
    scheme: slate
    primary: blue
    accent: pink
  font:
    text: Roboto
    code: Roboto Mono
    
plugins:
  - blog
