site_name: Carolina Projects
site_url: https://carolfmoreira.github.io/carolina-projects/
theme:
  name: material
  palette:
    scheme: slate
    primary: blue
    accent: pink
  font:
    text: Roboto
    code: Roboto Mono
    
plugins:
  - blog
